spring:
  application:
    name:hijra_kyc

  datasource:
    url: jdbc:mysql://localhost:3306/hijra_kyc
    username: root
    password: reyanberoneday

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
