spring:
    application:
        name: Hijra_kyc
    datasource:
        url: jdbc:mysql://localhost:3306/hijra
        username: root
        password:
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
          hibernate:
              format_sql: true
              dialect: org.hibernate.dialect.MySQL8Dialect
server:
    port: 9090
    tomcat:
        max-part-count: 20
        max-swallow-size: -1