spring:
    application:
        name: Hijra_kyc
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 10MB
    datasource:
        url: jdbc:mysql://localhost:3306/hijra__kyc
        username: root
        password: 'reyanberoneday'
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
              format_sql: false
              dialect: org.hibernate.dialect.MySQL8Dialect
server:
    port: 9090
    tomcat:
        max-part-count: 20
        max-swallow-size: -1